name: CI

on:
  push:
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Evaluate flake
        run: nix flake check --no-build --show-trace
      - name: Build Bixby Studio
        run: nix build .#bixby-studio --print-build-logs
